### ISSUE TITLE
Database migration - Node tmate@tmate.example.com is not running!

### ISSUE THREAD

**Issue by pini-gh** [tmate-io/tmate-master#14]
Hi,

I'm trying to run database migration as instructed at https://github.com/tmate-io/tmate-master/issues/1#issuecomment-562598733. But it fails at lauching an elixir shell:
```
$ docker exec -it tmate-master bash
bash-4.4$ bin/tmate remote_console
Node tmate@tmate.example.com is not running!
```
The master instance's logs don't give any clue:
```
$ docker logs -f tmate-master
16:37:45.752 [info] [swarm on tmate@tmate.example.com] [tracker:init] started
16:37:45.871 [info] Running TmateWeb.Endpoint with cowboy 2.7.0 at 0.0.0.0:4000 (http)
16:37:45.876 [info] Access TmateWeb.Endpoint at https://tmate.example.com
16:37:50.754 [info] [swarm on tmate@tmate.example.com] [tracker:cluster_wait] joining cluster..
16:37:50.754 [info] [swarm on tmate@tmate.example.com] [tracker:cluster_wait] no connected nodes, proceeding without sync
```
The web interface shows up correctly at https://tmate.example.com.

Here is the related docker-compose snippet:
```
  tmate-master:
    image: tmate/tmate-master:latest
    container_name: tmate-master
    # https://github.com/tmate-io/tmate-master/issues/13#issuecomment-787470427
    hostname: tmate-1
    restart: unless-stopped
    expose:
    - 4000
    environment:
      MASTER_BASE_URL: https://tmate.example.com/
      ERL_COOKIE: myerlcookie
      ERL_NODE_NAME: tmate.example.com
      # ** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
      SECRET_KEY_BASE: 0123456789abcdefghijklmnopqrstuvwxyz=0123456789abcdefghijklmnopqrstuvwxyz
      INTERNAL_API_AUTH_TOKEN: myinternalapiauthtoken
      PG_URI: postgres://tmate:postgrespassword@tmate-db:5432/tmate
      PG_POOLSIZE: 1
    networks:
      bridge:
      internal:
```

Thanks in advance.

**Comment by pini-gh** [comment]
This setting, where `<hostname>.<domainname>` matches `ERL_NODE_NAME` solves the problem:
```
  tmate-master:
    image: tmate/tmate-master:latest
    container_name: tmate-master
    # https://github.com/tmate-io/tmate-master/issues/13#issuecomment-787470427
    hostname: tmate-1
    domainname: example.com
    restart: unless-stopped
    expose:
    - 4000
    environment:
      MASTER_BASE_URL: https://tmate.example.com/
      ERL_COOKIE: myerlcookie
      ERL_NODE_NAME: tmate-1.example.com
      # ** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
      SECRET_KEY_BASE: 0123456789abcdefghijklmnopqrstuvwxyz=0123456789abcdefghijklmnopqrstuvwxyz
      INTERNAL_API_AUTH_TOKEN: myinternalapiauthtoken
      PG_URI: postgres://tmate:postgrespassword@tmate-db:5432/tmate
      PG_POOLSIZE: 1
    networks:
      bridge:
      internal:
```
```
$ docker exec -it tmate-master bash
bash-4.4$ bin/tmate remote_console
Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Interactive Elixir (1.9.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(tmate@tmate-1.example.com)1> 
```
